### ISSUE TITLE
Clustering the port number?

### ISSUE THREAD

**Issue by shadowbooker** [namshi/clusterjs#5]
Hey, 

Quick question about your clusterjs project. The testApp that you created listens on port 9516 (or something like that), when you're actually going to your app.js file via TCP, a 127.0.0.1:9516 clustered with clusterjs would get divvy'd out how?

clusterjs listens on 9516
- worker 1 
- worker 2
- worker 3

Does worker 1 need to listen ton 9517, worker 2 on 9518, and worker 3 on 9619 and clusterjs picks the connection to use? or how does that work? Does it use round robin on the workers to pick one thats free?

Thanks, 
Michael

**Comment by unlucio** [comment]
nope, they can all listen on the same port as stated in node's doc https://nodejs.org/api/cluster.html#cluster_cluster :)
